
export const cakesData = [
  {
    category: "Linha do Momento",
    items: [
      "Chocomix",
      "Abacaxi",
      "Abacaxi c/ Ameixa",
      "Baba de Moça",
      "Crocante",
      "Cuca de Goiabada e Moça",
      "Pêssego",
      "Gelado de Abacaxi",
    ],
  },
  {
    category: "Bolos Tradicionais",
    items: [
      "À Francesa",
      "Abacaxi c/ Coco",
      "Baba de Moça c/ Doce de Leite",
      "Beijinho",
      "Bolo da Vovó",
      "Bolo de Chocolate Vegano",
      "Brigadeiro c/ Baba de Moça",
      "Brigadeiro II",
      "Brigadeiro Tradicional",
      "Chifon",
      "Chocolate c/ Amendoim",
      "Chocolate c/ Crocante",
      "Delícia de Abacaxi",
      "Delícia de Coco",
      "Delícia de Coco II",
      "Dois Amores",
      "Ganache de Limão",
      "Tapioca c/ Coco e Moça®",
    ],
  },
  {
    category: "Bolos Clássicos",
    items: [
      "Abacaxi c/ Leite Condensado",
      "Aerado",
      "Alpes Suíços",
      "Alpino®",
      "Ameixa",
      "Banoffee",
      "Bolo Ana",
      "Bolo da Maria",
      "Bolo de Pimenta",
      "Bolo feito c/ Nescau®",
      "Bolo Fini Beijos Lançamento",
      "Bolo Fini Dentadura Lançamento",
      "Bolo Moça® Churros",
      "Bolo Moça® Pudim",
      "Bombom Branco",
      "Choc Rosa",
      "Chocolate c/ Maracujá",
      "Chocomoça®",
      "Delícia de Café",
      "Delícia de Leite com Limão",
      "Delícia de Leite Ninho®",
      "Delícia de Leite Ninho® II",
      "Delícia de Leite Ninho c/ Abacaxi",
      "Delícia de Uva com Abacaxi",
      "Frutas Amarelas",
      "Limão Siciliano",
      "Maracujá",
      "Olho de Sogra",
      "Paçoquinha",
      "Trufado",
      "Valsa de Chocolate",
    ],
  },
  {
    category: "Bolos Especiais",
    items: [
      "Abóbora c/ Cocada",
      "Aerado II",
      "Baba de Moça c/ Nozes",
      "Bolo feito c/ Galak®",
      "Bolo Moça® Romeu",
      "Bombom Branco Trufado",
      "Cartola",
      "Chocolate Branco",
      "Cupuaçu c/ Castanha-do-Pará",
      "Delícia de Castanha Trufado",
      "Delícia de Cereja (Floresta Negra)",
      "Delícia de Chocolate",
      "Delícia de Leite Trufado",
      "Delícia de Leite c/ Nozes",
      "Delícia de Nozes",
      "Dom Sodiê",
      "Frutas Vermelhas",
      "Magia",
      "Meio Amargo",
      "Nozes",
      "Parmesão e Doce de Leite",
      "Red Velvet (Perfil Americano)",
      "Red Velvet (Perfil Brasileiro)",
      "Trufas Brancas c/ Gotas",
      "Trufas Brancas c/ Nozes",
      "Trufas Brancas c/ Nozes e Damasco",
      "Trufado com Cereja",
      "Trufado c/ Ganache de Limão",
      "Trufado c/ Gotas de Chocolate",
      "Trufado Preto e Branco",
    ],
  },
  {
    category: "Especiais com Morango",
    items: [
      "Alaska",
      "Alpes Suíços c/ Morangos",
      "Bombom Branco c/ Morangos",
      "Brigadeiro c/ Creme e Morangos",
      "Chocomix c/ Morangos",
      "Chocotrufas c/ Morangos",
      "Delícia de Coco c/ Morangos",
      "Delícia de Leite c/ Brigadeiro e Morangos",
      "Delícia de Leite c/ Morangos",
      "Delícia de Morango",
      "Iogurte II",
      "Morango",
      "Morango c/ Crocante",
      "Morango c/ Leite Condensado",
      "Morango Trufado c/ Leite Condensado",
      "Napolitano",
      "Salada de Frutas",
      "Sodiê",
      "Sofia Rosa",
      "Trufado c/ Iogurte",
      "Trufado Preto e Branco c/ Morangos",
      "Valsa de Chocolate c/ Morangos",
    ],
  },
];
